management:
  endpoint:
    web:
      exposure:
        include: '*'

springdoc:
  api-docs:
    enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapi?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&createDatabaseIfNotExit=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  app:
    cors:
      allowed-origins: '*'
      allowed-methods: '*'
      allowed-headers: '*'
      exposed-headers: 'Authorization,Link,X-Total-Count,Set-Cookie,X-Auth-Token,x-api-key'
      max-age: 1800
    jwt:
      password: d2Fzd29uZGVyZmlsbG5vaXNlc3BsaXRjcm93ZHNob3R1bmRlcmFycm93dGhyb3VnaG8=
      expiration-time: 600000

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

